WHITESPACE    = _{ " " | "\t" | NEWLINE }
BLOCK_COMMENT = _{ "/*" ~ (BLOCK_COMMENT | !"*/" ~ ANY)* ~ "*/" }
COMMENT       = _{ BLOCK_COMMENT | (dbl_slash ~ (!NEWLINE ~ ANY)*) }
__            = _{ WHITESPACE }

// Broad Keywords

kw_null   =  { "null" }
kw_true   =  { "true" }
kw_false  =  { "false" }
kw_newat  =  { "newat" }
kw_fn     =  { "fn" }
kw_return = _{ "return" }
kw_switch = _{ "switch" }
kw_case   = _{ "case " }
kw_then   = _{ "then " }
kw_if     = _{ "if " }
kw_else   = _{ "else " }
kw_print  = _{ "print " }
kw_where  = _{ "where " }
kw_let    = _{ "let " }

// Operator Keywords

kw_not    = @{ "not" ~ __ }

kw_mod    = @{ "mod" ~ __ }
kw_in     = @{ "in" ~ __ }
kw_notin  = @{ "notin" ~ __ }
kw_subset = @{ "subset" ~ __ }
kw_impl   = @{ "impl" ~ __ }
kw_iff    = @{ "iff" ~ __ }
kw_and    = @{ "and" ~ __ }
kw_or     = @{ "or" ~ __ }
kw_union  = @{ "union" ~ __ }
kw_inter  = @{ "inter" ~ __ }
kw_div    = @{ "div" ~ __ }
kw_with   = @{ "with" ~ __ }
kw_less   = @{ "less" ~ __ }

kw_exists = @{ "exists" ~ __ }
kw_forall = @{ "forall" ~ __ }
kw_choose = @{ "choose" ~ __ }

// Silent non-operator symbols

semicolon  = _{ ";" }
colon      = _{ ":" }
comma      = _{ "," }
lodash     = _{ "_" }
b_slash    = _{ "\\" }
quote      = _{ "\"" }
dot        = _{ "." }
qst        = _{ "?" }
eq         = _{ "=" }
l_brace    = _{ "{" }
r_brace    = _{ "}" }
l_paren    = _{ "(" }
r_paren    = _{ ")" }
l_brack    = _{ "[" }
r_brack    = _{ "]" }
reduce     = _{ "%" }
arrow      = _{ "->" }
fat_arrow  = _{ "=>" }
tall_arrow = _{ "|>" }
dbl_slash  = _{ "//" }
dbl_dot    = _{ ".." }
tpl_dot    = _{ "..." }

// Direct operator symbols

plus     = { "+" }
dash     = { "-" }
star     = { "*" }
slash    = { "/" }
percent  = { "%" }
bang     = { "!" }
hash     = { "#" }
caret    = { "^" }
dollar   = { "$" }
tilde    = { "~" }
amp      = { "&" }
pipe     = { "|" }
at       = { "@" }
lt       = { "<" }
gt       = { ">" }
dbl_eq   = { "==" }
bang_eq  = { "!=" }
lt_eq    = { "<=" }
gt_eq    = { ">=" }
dbl_star = { "**" }
dbl_amp  = { "&&" }
dbl_pipe = { "||" }
dbl_qst  = { "??" }
dbl_lt   = { "<<" }
dbl_gt   = { ">>" }

// Direct Operator symbols (prefix duplicates)
// These are needed because the PRATT parser will freak out if
// the same rule is used for 2 different entries. They can be
// the same symbol, just not the same rule.
dash_pre  = { "-" }
caret_pre = { "^" }
amp_pre   = { "&" }

// Operator Groups

nested_expr = { l_paren ~ expr ~ r_paren }

prefix_op = _{
  | dash_pre
  | caret_pre
  | amp_pre
  | plus
  | hash
  | bang
  | dollar
  | tilde
  | kw_not
}

reduce_op = { reduce ~ (ident | nested_expr | binary_op) }

infix_inject_op = { dot ~ (ident | nested_expr) }

// Precedence is handled by the PRATT_PARSER in the `./parser.rs` file
binary_op = _{
  | reduce_op
  | infix_inject_op
  | dbl_qst
  | dbl_star
  | dbl_lt
  | dbl_gt
  | dbl_eq
  | dbl_amp
  | dbl_pipe
  | lt_eq
  | gt_eq
  | bang_eq
  | at
  | star
  | slash
  | percent
  | plus
  | dash
  | amp
  | pipe
  | caret
  | lt
  | gt
  | kw_div
  | kw_inter
  | kw_mod
  | kw_with
  | kw_less
  | kw_union
  | kw_in
  | kw_notin
  | kw_subset
  | kw_and
  | kw_or
  | kw_impl
  | kw_iff
}

select_op = _{
  | kw_exists
  | kw_forall
  | kw_choose
}

// Literals

atom_keep =  { (ASCII_ALPHANUMERIC | lodash)+ }
atom      = ${ colon ~ atom_keep }

number_base    = @{ ASCII_DIGIT+ }
number_decimal = @{ (dot ~ ASCII_DIGIT+)? }
number_exp     = @{ ((^"e" | ^"f") ~ (plus | dash)? ~ ASCII_DIGIT+)? }
number         = ${ number_base ~ number_decimal ~ number_exp }

string_char = _{
  | !(quote | b_slash) ~ ANY
  | b_slash ~ (quote | b_slash | "n" | "t")
}
string_keep =  { string_char* }
string      = ${ quote ~ string_keep ~ quote }

ident = @{ (ASCII_ALPHA | lodash) ~ (ASCII_ALPHANUMERIC | lodash)* }

tuple_literal = { l_brack ~ former? ~ r_brack }
set_literal   = { l_brace ~ former? ~ r_brace }

// map_literal = { l_brace ~ r_brace }

// Former

iterator_former       =  { expr ~ colon ~ iterator }
inclusive_range_op    =  { dbl_dot }
exclusive_range_op    =  { tpl_dot }
range_op              = _{ exclusive_range_op | inclusive_range_op }
range_former          =  { expr ~ range_op ~ expr }
interval_range_former =  { expr ~ comma ~ range_former }

former = _{
  | iterator_former
  | interval_range_former // must come before literal former
  | range_former
  | expr_list
}

// Bound (The LHS of an assignment / destructuring)

// An outermost bound can be a identifier or a list of bounds
// Inside a bound-list, a bound can also be a `~`, which is used
// to skip element in an assignment

bound = _{
  | ident
  | bound_list_wrapped
}

bound_rest = ${ tpl_dot ~ ident? }

bound_list_inner = _{
  | tilde
  | ident
  | bound_rest
  | bound_list_wrapped
}

bound_list         =  { bound_list_inner ~ (comma ~ bound_list_inner)* ~ comma? }
bound_list_wrapped = _{ l_brack ~ bound_list? ~ r_brack }

// Iterators

silent_in              = _{ "in" }
in_iterator            =  { bound_list ~ silent_in ~ expr }
select_iterator_single =  { bound ~ eq ~ ident ~ l_paren ~ bound ~ r_paren }
// select_iterator_multi  =  { bound ~ eq ~ ident ~ l_brace ~ bound ~ r_brace }
single_iterator        = _{
  | in_iterator
  | select_iterator_single
  // | select_iterator_multi
}
iterator_list          =  { single_iterator ~ (comma ~ single_iterator)* ~ comma? }
iterator_where         = _{ arrow | kw_where }
iterator               = !{ iterator_list ~ (iterator_where ~ expr)? }

// Functions

req_param = ${ ident }
opt_param = ${ ident ~ qst }

// Order is significant
param = _{
  | opt_param
  | req_param
}

param_list = { l_paren ~ (param ~ (comma ~ param)*)? ~ comma? ~ r_paren }

func_literal = { param_list ~ fat_arrow ~ expr }

// Postfix Selectors

fn_call     = { l_paren ~ expr_list? ~ r_paren }
index_call  = { l_brack ~ expr ~ r_brack }
pick_call   = { l_brace ~ expr ~ r_brace }
slice_call  = { l_brack ~ expr? ~ range_op ~ expr? ~ r_brack }
postfix_selector = _{
  | fn_call
  | index_call
  | slice_call
  | pick_call
}

// Expressions

primary = _{
  | kw_null
  | kw_newat
  | kw_true
  | kw_false
  | atom
  | number
  | string
  | tuple_literal
  | set_literal
  | func_literal
  | ident // Must come after any keywords
  | nested_expr
}

expr_unit = _{ prefix_op* ~ primary ~ postfix_selector* }
gen_expr = !{ expr_unit ~ (binary_op ~ expr_unit)* }

cond_then = _{
  | tall_arrow
  | kw_then
}

ternary_expr = !{ kw_if ~ expr ~ qst ~ stmt ~ colon ~ stmt }

// The only kinds of expression which can appear inside a case condition
// are the non-conditional kinds which can be immediately executed without
// jumps.
case_expr = _{
  | tilde
  | select_expr
  | gen_expr
}
case = { kw_case ~ case_expr ~ cond_then ~ stmt }
switch_expr = !{
  kw_switch
  ~ nested_expr?
  ~ l_brace
  ~ case ~ (comma ~ case)* ~ comma?
  ~ r_brace
}

select_expr = !{ select_op ~ iterator }

block_expr = !{ l_brace ~ stmt_list_with_capture ~ r_brace }

expr = _{
  | ternary_expr
  | switch_expr
  | select_expr
  | gen_expr
  | block_expr
}

expr_list = !{ expr ~ (comma ~ expr)* ~ comma? }

// Statements

return_stmt  = ${ kw_return ~ (__ ~ expr)? }
print_stmt   = ${ kw_print ~ expr }
assign_stmt  =  { bound ~ eq ~ expr }
// cond_stmt    = !{ kw_if ~ expr ~ cond_then ~ stmt }

stmt = _{
  | return_stmt
  | print_stmt
  // | cond_stmt
  | assign_stmt
  | expr
}

stmt_list = { (stmt ~ semicolon+)* }
stmt_list_with_capture = { stmt_list ~ stmt? }

// Program

raw_program = { SOI ~ stmt_list_with_capture ~ EOI }
